ARG PYTHON_VERSION=3.12
ARG CMAKE_MAX_JOBS
ARG CUDA_VERSION=12.9.1
ARG CUDA_ARCHS
ARG VLLM_BASE_IMAGE=vllm/vllm-openai:v0.18.1
ARG VLLM_BUILD_BASE_IMAGE=vllm/vllm-openai:v0.18.1
ARG VLLM_VERSION=v0.18.1
ARG VLLM_TORCH_VERSION=2.10.0
ARG VLLM_TORCH_CUDA_VERSION=${CUDA_VERSION}
ARG VLLM_LMCACHE_VERSION=0.4.2
ARG VLLM_OMNI_COMMIT=f55ea280

FROM ${VLLM_BUILD_BASE_IMAGE} AS vllm-build
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV VLLM_VERSION=${VLLM_VERSION} \
    VLLM_TORCH_VERSION=${VLLM_TORCH_VERSION} \
    VLLM_TORCH_CUDA_VERSION=${VLLM_TORCH_CUDA_VERSION}


FROM vllm-build AS vllm-build-lmcache
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

## Build LMCache

ARG CMAKE_MAX_JOBS
ARG VLLM_LMCACHE_VERSION

ENV VLLM_LMCACHE_VERSION=${VLLM_LMCACHE_VERSION}

RUN <<EOF
    # LMCache
    # Ref https://github.com/LMCache/LMCache/blob/5afe9688b3519074b9915e7b3acf871328250150/docs/source/getting_started/installation.rst?plain=1#L67-L129.

    IFS="." read -r CUDA_MAJOR CUDA_MINOR CUDA_PATCH <<< "${VLLM_TORCH_CUDA_VERSION}"

    CMAKE_MAX_JOBS="${CMAKE_MAX_JOBS}"
    if [[ -z "${CMAKE_MAX_JOBS}" ]]; then
        CMAKE_MAX_JOBS="$(( $(nproc) / 2 ))"
    fi
    if (( $(echo "${CMAKE_MAX_JOBS} > 8" | bc -l) )); then
        CMAKE_MAX_JOBS="8"
    fi
    LC_CUDA_ARCHS="${CUDA_ARCHS}"
    if [[ -z "${LC_CUDA_ARCHS}" ]]; then
        if (( $(echo "${CUDA_MAJOR}.${CUDA_MINOR} < 12.9" | bc -l) )); then
            LC_CUDA_ARCHS="7.5 8.0+PTX 8.9 9.0 10.0+PTX 12.0+PTX"
        else
            LC_CUDA_ARCHS="7.5 8.0+PTX 8.9 9.0 10.0 10.3 12.0 12.1+PTX"
        fi
    fi
    export MAX_JOBS="${CMAKE_MAX_JOBS}"
    export TORCH_CUDA_ARCH_LIST="${LC_CUDA_ARCHS}"
    export NVCC_THREADS=1
    echo "Building LMCache with the following environment variables:"
    env

    # Build
    git -C /tmp clone --recursive --shallow-submodules \
        --depth 1 --branch v${VLLM_LMCACHE_VERSION} --single-branch \
        https://github.com/LMCache/LMCache.git lmcache
    pushd /tmp/lmcache \
        && sed -i "s/\"torch==.*\"/\"torch\"/g" /tmp/lmcache/pyproject.toml \
        && cat /tmp/lmcache/pyproject.toml \
        && uv pip install cuda-bindings==12.9.4 \
        && python -v -m build --no-isolation --wheel \
        && tree -hs /tmp/lmcache/dist \
        && mv /tmp/lmcache/dist /workspace

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/* \
        && ccache --clear --clean
EOF


FROM vllm-build AS vllm-build-omni
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

## Build Omni

ARG CMAKE_MAX_JOBS
ARG VLLM_OMNI_COMMIT

ENV VLLM_OMNI_COMMIT=${VLLM_OMNI_COMMIT}

RUN <<EOF
    # Omni

    if [[ -z "${VLLM_OMNI_COMMIT}" ]]; then
        echo "Skipping vLLM Omni build for ${TARGETARCH}..."
        exit 0
    fi

    IFS="." read -r CUDA_MAJOR CUDA_MINOR CUDA_PATCH <<< "${VLLM_TORCH_CUDA_VERSION}"

    CMAKE_MAX_JOBS="${CMAKE_MAX_JOBS}"
    if [[ -z "${CMAKE_MAX_JOBS}" ]]; then
        CMAKE_MAX_JOBS="$(( $(nproc) / 2 ))"
    fi
    if (( $(echo "${CMAKE_MAX_JOBS} > 4" | bc -l) )); then
        CMAKE_MAX_JOBS="4"
    fi
    VL_CUDA_ARCHS="${CUDA_ARCHS}"
    if [[ -z "${VL_CUDA_ARCHS}" ]]; then
        if (( $(echo "${CUDA_MAJOR}.${CUDA_MINOR} < 12.9" | bc -l) )); then
            VL_CUDA_ARCHS="7.5 8.0+PTX 8.9 9.0 10.0+PTX 12.0+PTX"
        else
            VL_CUDA_ARCHS="7.5 8.0+PTX 8.9 9.0 10.0 10.3 12.0 12.1+PTX"
        fi
    fi
    export MAX_JOBS="${CMAKE_MAX_JOBS}"
    export TORCH_CUDA_ARCH_LIST="${VL_CUDA_ARCHS}"
    export NVCC_THREADS=1
    echo "Building vLLM Omni with the following environment variables:"
    env

    # Build
    git -C /tmp clone --recursive --shallow-submodules \
        https://github.com/vllm-project/vllm-omni vllm_omni \
        && pushd /tmp/vllm_omni \
        && git checkout ${VLLM_OMNI_COMMIT} \
        && git submodule update --init --recursive
    pushd /tmp/vllm_omni \
        && if [[ "${TARGETARCH}" == "arm64" ]]; then sed -i "/\"fa3-fwd.*\"/d" /tmp/vllm_omni/pyproject.toml; fi \
        && if [[ "${TARGETARCH}" == "arm64" ]]; then sed -i "/fa3-fwd.*/d" /tmp/vllm_omni/requirements/cuda.txt; fi \
        && python -v -m build --no-isolation --wheel \
        && tree -hs /tmp/vllm_omni/dist \
        && mv /tmp/vllm_omni/dist /workspace

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF


FROM ${VLLM_BASE_IMAGE} AS vllm
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

ENV UV_SYSTEM_PYTHON=1 \
    UV_PRERELEASE=allow \
    UV_SKIP_WHEEL_FILENAME_CHECK=1

## Install Ray

RUN <<EOF
    # Ray

    # Install Ray Client and Default
    RAY_VERSION=2.54.1
    cat <<EOT >/tmp/requirements.txt
ray[cgraph]==${RAY_VERSION}
ray[client]==${RAY_VERSION}
ray[default]==${RAY_VERSION}
EOT
    uv pip install \
        -r /tmp/requirements.txt

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Install CuDNN

RUN <<EOF
    # CuDNN

    IFS="." read -r CUDA_MAJOR CUDA_MINOR CUDA_PATCH <<< "${VLLM_TORCH_CUDA_VERSION}"

    # Install
    cat <<EOT >/tmp/requirements.txt
nvidia-cudnn-cu${CUDA_MAJOR}>=9.16.0.29
nvidia-cudnn-frontend>=1.17.0
EOT
    uv pip install \
        -r /tmp/requirements.txt

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Install Omni

RUN --mount=type=bind,from=vllm-build-omni,source=/,target=/omni,rw <<EOF
    # Omni

    if [[ ! -d /omni/workspace ]]; then
        echo "Skipping vLLM Omni installation for ${TARGETARCH}..."
        exit 0
    fi

    # Install
    uv pip install --no-build-isolation \
        /omni/workspace/*.whl

    # Dependencies
    cat <<EOT >/tmp/requirements.txt
onnxruntime
sox
EOT
    uv pip install \
        -r /tmp/requirements.txt

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Install LMCache

RUN --mount=type=bind,from=vllm-build-lmcache,source=/,target=/lmcache,rw <<EOF
    # LMCache

    # Install
    uv pip install --no-build-isolation \
        /lmcache/workspace/*.whl

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Postprocess

RUN <<EOF
    # Postprocess

    # Review
    uv pip tree \
        --package vllm \
        --package vllm-omni \
        --package flashinfer-python \
        --package torch \
        --package triton \
        --package deep-gemm \
        --package deep-ep \
        --package lmcache \
        --package mooncake-transfer-engine \
        --package ray
EOF

## Patch

RUN --mount=type=bind,target=/workspace,rw <<EOF
    # Patch

    tree -hs /workspace/patches
    pushd $(pip show vllm | grep Location: | cut -d" " -f 2) \
        && patch -p1 < /workspace/patches/vllm/*.patch
    if pip show vllm_omni > /dev/null 2>&1; then \
        pushd $(pip show vllm_omni | grep Location: | cut -d" " -f 2) \
            && patch -p1 < /workspace/patches/vllm_omni/*.patch; \
    fi
EOF

## Entrypoint

ENV RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=1 \
    SAFETENSORS_FAST_GPU=1 \
    RUNAI_STREAMER_MEMORY_LIMIT=0 \
    RUNAI_STREAMER_LOG_TO_STDERR=1 \
    RUNAI_STREAMER_LOG_LEVEL=INFO

WORKDIR /
ENTRYPOINT [ "tini", "--" ]
