ARG PYTHON_VERSION=3.12
ARG CMAKE_MAX_JOBS
ARG CUDA_VERSION=13.0.1
ARG CUDA_ARCHS
ARG VLLM_BASE_IMAGE=vllm/vllm-openai:v0.20.1
ARG VLLM_VERSION=0.20.1
ARG VLLM_TORCH_VERSION=2.12.0
ARG VLLM_TORCH_CUDA_VERSION=${CUDA_VERSION}
ARG VLLM_OMNI_COMMIT=704b6bb6

FROM ${VLLM_BASE_IMAGE} AS vllm-build
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

## Install Tools

ENV DEBIAN_FRONTEND=noninteractive \
    LANG='en_US.UTF-8' \
    LANGUAGE='en_US:en' \
    LC_ALL='en_US.UTF-8'

RUN <<EOF
    # Tools

    # Refresh
    apt-get update -y && apt-get install -y --no-install-recommends \
        software-properties-common apt-transport-https \
        ca-certificates gnupg2 lsb-release gnupg-agent \
      && apt-get update -y

    # Install
    apt-get install -y --no-install-recommends \
        ca-certificates build-essential binutils bash openssl \
        curl wget aria2 \
        git git-lfs \
        unzip xz-utils \
        tzdata locales \
        iproute2 iputils-ping ifstat net-tools dnsutils pciutils ipmitool \
        rdma-core rdmacm-utils infiniband-diags \
        procps sysstat htop \
        tini vim jq bc tree

    # Update locale
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

    # Update timezone
    rm -f /etc/localtime \
        && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
        && echo "Asia/Shanghai" > /etc/timezone \
        && dpkg-reconfigure --frontend noninteractive tzdata

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/* \
        && rm -rf /var/cache/apt
EOF

## Prepare Python

ARG PYTHON_VERSION

ENV PYTHON_VERSION=${PYTHON_VERSION}

RUN <<EOF
    # Python

    # Update alternatives
    if ! command -v python >/dev/null 2>&1 \
        && command -v python${PYTHON_VERSION} >/dev/null 2>&1; then
        update-alternatives --install /usr/bin/python python $(which python${PYTHON_VERSION}) 1
    fi
EOF

ENV PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_ROOT_USER_ACTION=ignore

## Prepare Python Buildkit

RUN <<EOF
    # Buildkit

    cat <<EOT >/tmp/requirements.txt
build
cmake<4
wheel
pybind11<3
Cython
EOT
    pip install -r /tmp/requirements.txt

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Prepare Envs

ARG CUDA_VERSION
ARG CUDA_ARCHS

ENV CUDA_HOME="/usr/local/cuda" \
    CUDA_VERSION=${CUDA_VERSION} \
    CUDA_ARCHS=${CUDA_ARCHS}

ENV UV_SYSTEM_PYTHON=1 \
    UV_PRERELEASE=allow \
    UV_SKIP_WHEEL_FILENAME_CHECK=1 \
    UV_NO_CACHE=1 \
    UV_HTTP_TIMEOUT=500 \
    UV_INDEX_STRATEGY="unsafe-best-match"

ARG VLLM_VERSION
ARG VLLM_TORCH_VERSION
ARG VLLM_TORCH_CUDA_VERSION

ENV VLLM_VERSION=${VLLM_VERSION} \
    VLLM_TORCH_VERSION=${VLLM_TORCH_VERSION} \
    VLLM_TORCH_CUDA_VERSION=${VLLM_TORCH_CUDA_VERSION}


FROM vllm-build AS vllm-build-omni
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

## Build Omni

ARG CMAKE_MAX_JOBS
ARG VLLM_OMNI_COMMIT

ENV VLLM_OMNI_COMMIT=${VLLM_OMNI_COMMIT}

RUN <<EOF
    # Omni

    rm -rf /workspace

    if [[ -z "${VLLM_OMNI_COMMIT}" ]]; then
        echo "Skipping vLLM Omni build for ${TARGETARCH}..."
        exit 0
    fi

    IFS="." read -r CUDA_MAJOR CUDA_MINOR CUDA_PATCH <<< "${VLLM_TORCH_CUDA_VERSION}"

    CMAKE_MAX_JOBS="${CMAKE_MAX_JOBS}"
    if [[ -z "${CMAKE_MAX_JOBS}" ]]; then
        CMAKE_MAX_JOBS="$(( $(nproc) / 2 ))"
    fi
    if (( $(echo "${CMAKE_MAX_JOBS} < 4" | bc -l) )); then
        CMAKE_MAX_JOBS="4"
    fi
    VL_CUDA_ARCHS="${CUDA_ARCHS}"
    if [[ -z "${VL_CUDA_ARCHS}" ]]; then
        if (( $(echo "${CUDA_MAJOR}.${CUDA_MINOR} < 12.9" | bc -l) )); then
            VL_CUDA_ARCHS="7.5 8.0+PTX 8.9 9.0 10.0+PTX 12.0+PTX"
        else
            VL_CUDA_ARCHS="7.5 8.0+PTX 8.9 9.0 10.0 10.3 12.0 12.1+PTX"
        fi
    fi
    export MAX_JOBS="${CMAKE_MAX_JOBS}"
    export TORCH_CUDA_ARCH_LIST="${VL_CUDA_ARCHS}"
    export NVCC_THREADS=1
    echo "Building vLLM Omni with the following environment variables:"
    env

    # Build
    git -C /tmp clone --recursive --shallow-submodules \
        https://github.com/vllm-project/vllm-omni vllm_omni \
        && pushd /tmp/vllm_omni \
        && git checkout ${VLLM_OMNI_COMMIT} \
        && git submodule update --init --recursive
    pushd /tmp/vllm_omni \
        && if [[ "${TARGETARCH}" == "arm64" ]]; then sed -i "/\"fa3-fwd.*\"/d" /tmp/vllm_omni/pyproject.toml; fi \
        && if [[ "${TARGETARCH}" == "arm64" ]]; then sed -i "/fa3-fwd.*/d" /tmp/vllm_omni/requirements/cuda.txt; fi \
        && python -v -m build --no-isolation --wheel \
        && tree -hs /tmp/vllm_omni/dist \
        && mv /tmp/vllm_omni/dist /workspace

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF


FROM vllm-build AS vllm
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH

## Install Ray

RUN <<EOF
    # Ray

    # Install Ray Client and Default
    RAY_VERSION=2.55.1
    cat <<EOT >/tmp/requirements.txt
ray[cgraph]==${RAY_VERSION}
ray[client]==${RAY_VERSION}
ray[default]==${RAY_VERSION}
EOT
    uv pip install \
        -r /tmp/requirements.txt

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Install Omni

RUN --mount=type=bind,from=vllm-build-omni,source=/,target=/omni,rw <<EOF
    # Omni

    if [[ ! -d /omni/workspace ]]; then
        echo "Skipping vLLM Omni installation for ${TARGETARCH}..."
        exit 0
    fi

    # Install
    uv pip install --no-build-isolation \
        /omni/workspace/*.whl

    # Dependencies
    cat <<EOT >/tmp/requirements.txt
onnxruntime
sox
EOT
    uv pip install \
        -r /tmp/requirements.txt

    # Cleanup
    rm -rf /var/tmp/* \
        && rm -rf /tmp/*
EOF

## Postprocess

RUN <<EOF
    # Postprocess

    # Review
    uv pip tree \
        --package vllm \
        --package vllm-omni \
        --package flashinfer-python \
        --package torch \
        --package triton \
        --package deep-gemm \
        --package deep-ep \
        --package lmcache \
        --package mooncake-transfer-engine \
        --package ray
EOF

## Patch

RUN --mount=type=bind,target=/workspace,rw <<EOF
    # Patch

    tree -hs /workspace/patches
    pushd $(pip show vllm | grep Location: | cut -d" " -f 2) \
        && patch -p1 < /workspace/patches/vllm/*.patch
    if pip show vllm_omni > /dev/null 2>&1; then \
        pushd $(pip show vllm_omni | grep Location: | cut -d" " -f 2) \
            && patch -p1 < /workspace/patches/vllm_omni/*.patch; \
    fi
EOF

## Entrypoint

ENV RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES=1 \
    SAFETENSORS_FAST_GPU=1 \
    RUNAI_STREAMER_MEMORY_LIMIT=0 \
    RUNAI_STREAMER_LOG_TO_STDERR=1 \
    RUNAI_STREAMER_LOG_LEVEL=INFO

WORKDIR /
ENTRYPOINT [ "tini", "--" ]
